# Generated by Django 2.0 on 2018-03-06 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie_stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('auteur', models.CharField(max_length=42)),
                ('description', models.TextField(null=True)),
                ('lieu', models.CharField(max_length=200)),
                ('nombre_place', models.IntegerField()),
                ('inscription', models.BooleanField()),
                ('theme', models.CharField(max_length=100)),
                ('date_parution', models.DateTimeField(auto_now_add=True, verbose_name='Date de parution')),
                ('date', models.DateTimeField(verbose_name="Date de l'évènement")),
                ('is_visible', models.BooleanField(default=False, verbose_name='Article publié ?')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_evenement/')),
            ],
            options={
                'verbose_name': 'évènement',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('auteur', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('remuneration', models.CharField(max_length=20)),
                ('date_parution', models.DateTimeField(auto_now_add=True, verbose_name='Date de parution')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date de fin')),
                ('duree', models.IntegerField()),
                ('is_visible', models.BooleanField(default=False, verbose_name='Article publié ?')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_sc.Categorie_stage')),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_sc.Domaine')),
            ],
            options={
                'verbose_name': 'stage',
                'ordering': ['date_parution'],
            },
        ),
        migrations.CreateModel(
            name='Type_evenement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserEntreprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('signature', models.TextField(blank=True)),
                ('taille', models.CharField(max_length=255)),
                ('qualité', models.IntegerField()),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_sc.Domaine')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserEtudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('nom', models.CharField(max_length=255)),
                ('prénom', models.CharField(max_length=255)),
                ('notif_stage', models.BooleanField()),
                ('notif_evenement', models.BooleanField()),
                ('adresse', models.CharField(max_length=255)),
                ('cv', models.FileField(blank=True, null=True, upload_to='CVs/')),
                ('qualité', models.IntegerField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_sc.Institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('signature', models.TextField(blank=True)),
                ('qualité', models.IntegerField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_sc.Institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='evenement',
            name='type_evenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_sc.Type_evenement'),
        ),
    ]
