# Generated by Django 2.0 on 2018-03-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_sc', '0002_auto_20180306_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentreprise',
            name='qualité',
            field=models.IntegerField(default='2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinstitution',
            name='qualité',
            field=models.IntegerField(default='3'),
            preserve_default=False,
        ),
    ]
